# Generated by Django 3.2.7 on 2021-09-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(None, None), ('SPEAKER', 'Speaker'), ('PARTICIPANT', 'Participant')], default=None, max_length=40),
        ),
    ]
