# Generated by Django 3.2.7 on 2021-09-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0001_initial'),
        ('speaker', '0001_initial'),
        ('talk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='talks_p', to='participant.Participant'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='speakers',
            field=models.ManyToManyField(blank=True, related_name='talks_s', to='speaker.Speaker'),
        ),
    ]
