version: 2.1

orbs:
  python: circleci/python@1.2

workflows:
  build-and-test-workflow:
    jobs:
      - build-and-test

jobs:
  build-and-test:  
    docker:
      - image: cimg/python:3.9.6
      - image: postgres:9.6.2-alpine
        auth:
          username: tosinolawore
          password: $DOCKERHUB_PASSWORD  
        environment:
          POSTGRES_USER: aviyel
          POSTGRES_DB: aviyel_test
    steps:
      - checkout
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - python/install-packages:
          pkg-manager: pip
          # app-dir: ~/project/package-directory/  # If you're requirements.txt isn't in the root directory.
          # pip-dependency-file: test-requirements.txt  # if you have a different name for your requirements file, maybe one that combines your runtime and test requirements.
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            python3 manage.py test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: aviyel-test-result